import re
import argparse
from mimic4preprocessing.key_value_unit_processer import _create_dataset_config

def token_bin_range(args, inclusion_dict):
    if args is None:
        raise NotImplementedError

    elif args.bin.startswith('bin'):
        # bin{N}_exp{E}_th{T} -> percentile-bin threshold pickle name
        match = re.search(r'bin([^_]+)_exp([^_]+)_th([^_]+)', args.bin)
        if match:
            bin_v, exp_v, th_v = match.groups()
        else:
            print("형식이 맞지 않습니다.")
            raise NotImplementedError
        pkl_name = f'bin{bin_v}_weight{"False" if th_v == 1 else "True"}_exp{exp_v}_th{th_v}'
        return _create_dataset_config(pkl_name, inclusion_dict)

    else:
        raise NotImplementedError(f"Unsupported --bin: {args.bin}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    # Current saved path of preprocessed data
    parser.add_argument("--binning_threshold", type=str, default="mimic4preprocessing/unit_value_cleaning/data/")
    parser.add_argument("--downstream_tasks", type=str, default="/path/to/PFM_data/tensor_saved/")

    # Data Processing args
    parser.add_argument("--data", type=str, default='criteria1',
                        help='criteria is in - mimic4preprocessing/scripts/inclusion_criteria')
    parser.add_argument("--bin", type=str, default='bin10_exp1_th10',
                        help='value binning; thresholds live in mimic4preprocessing/unit_value_cleaning/data/ (generated by mimic4preprocessing/unit_value_cleaning/binning/make_bin.py). bin{N}_exp{E}_th{T} = N percentile bins, density-weight exponent E (exp0 = no weighting), weight-clip threshold T. Used: bin10_exp1_th10 [OURS], bin10_exp0_th10 [ETHOS generation baseline]. Also generated: bin10_exp{0.5,1.5,2}_th10.')
    parser.add_argument("--share_tokens", type=int, default=1, help='0 - not share token; use each bin'
                                                                    '1 - share token')
    parser.add_argument("--seq_gen", type=str, default='addQ', help='addQ - add info token with timestamp and '
                                                                    'addTS - share token'
                                                                    'NOadd - no adding info token')
    parser.add_argument("--objective", type=str, default='G2DYDTSP', help='G2DYDTSP - OURS. NTP - ETHOS baseline / downstream eval.')
    args = parser.parse_args()

    config = token_bin_range(args)
    for ky, itm in config.items():
        print(ky, itm)

