import argparse
import os
from datetime import datetime
from pfm_mimic4.model.timestamp_tf import TimestampTransformer
from pfm_mimic4.dataset.qa_dataset import get_datasets
from pfm_mimic4.tokenizer.multitype_tokenizer import MultiTypeTokenizer
from pfm_mimic4.tokenizer.tokenizing_setting import token_bin_range
from pfm_mimic4.exp.pfm_mixed_precision import TransformerTrainerDDP, initialize_ddp
from mimic4preprocessing.scripts.inclusion_criteria.criteria1 import criteria1
from mimic4preprocessing.key_value_unit_processer import key_value_unit_processer
from utils import *

# Repository root (this file lives at <repo>/pfm_mimic4/main.py).
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Committed value/unit binning + TTE thresholds shipped inside the repo.
_BINNING_DATA_DIR = os.path.join(_REPO_ROOT, "mimic4preprocessing", "unit_value_cleaning", "data") + os.sep
# Root of the preprocessed-data tree. Edit this path or set the PFM_DATA_ROOT
# environment variable to point at your preprocessing output directory.
DATA_ROOT = os.environ.get("PFM_DATA_ROOT", "/path/to/PFM_data")

parser = argparse.ArgumentParser()
# PFM args
parser.add_argument("--pred_max_dist_hr", type=int, default=24)

# Learning args
parser.add_argument("--lr", type=float, default=5e-4)
parser.add_argument("--warmup_steps", type=int, default=50)
parser.add_argument("--num_epochs", type=int, default=50)
parser.add_argument("--early_stop_patience", type=int, default=40)
parser.add_argument("--batch_size", type=int, default=72)
parser.add_argument("--checkpoint_dir", type=str, default=os.path.join(DATA_ROOT, "result_pretrained") + os.sep)
parser.add_argument("--result_dir", type=str, default=os.path.join(DATA_ROOT, "result_pretrained") + os.sep)
parser.add_argument("--resume_pretrain", type=str, default=None,
                    help='Resume pretraining from existing folder. '
                         'e.g. max_len2048_overlap512_h512_h8_l6_ff2048/fcriteria1_bin10_exp1_th10_share0_NOadd_G2DYDTSP_rope:U1M1TS40_0324:150100')

#Masking args
parser.add_argument("--mask_feature_p", type=float, default=0.1)
parser.add_argument("--mask_token_p", type=float, default=0.1)

# Model args
parser.add_argument("--model_hidden_dim", type=int, default=512)
parser.add_argument("--model_num_heads", type=int, default=8)
parser.add_argument("--model_num_layers", type=int, default=6)
parser.add_argument("--model_d_ff", type=int, default=2048)
parser.add_argument("--model_dropout", type=float, default=0.1)

# Data args
parser.add_argument("--sample_max_length", type=int, default=2048)
parser.add_argument("--sample_overlap", type=int, default=512)
parser.add_argument("--sample_n_workers", type=int, default=16) # currently in preprocessing
parser.add_argument("--num_workers", type=int, default=8)
parser.add_argument("--data_dir", type=str, default=os.path.join(DATA_ROOT, "PFM_pretraining", "tensor_saved") + os.sep)
parser.add_argument("--qa_table_dir", type=str, default=os.path.join(DATA_ROOT, "PFM_pretraining") + os.sep)

# Value/unit binning + TTE thresholds shipped in-repo (mimic4preprocessing/unit_value_cleaning/data).
parser.add_argument("--binning_threshold", type=str, default=_BINNING_DATA_DIR)
parser.add_argument("--tte_threshold", type=str, default=os.path.join(_BINNING_DATA_DIR, "for_tte", "edge-[0.01, 0.05].pkl"))

# Data Processing args
parser.add_argument("--data", type=str, default='criteria1', help='criteria is in - mimic4preprocessing/scripts/inclusion_criteria')
parser.add_argument("--bin", type=str, default='bin10_exp1_th10',
                        help='value binning; thresholds live in mimic4preprocessing/unit_value_cleaning/data/ (generated by mimic4preprocessing/unit_value_cleaning/binning/make_bin.py). bin{N}_exp{E}_th{T} = N percentile bins, density-weight exponent E (exp0 = no weighting), weight-clip threshold T. Used: bin10_exp1_th10 [OURS], bin10_exp0_th10 [ETHOS generation baseline]. Also generated: bin10_exp{0.5,1.5,2}_th10.')
parser.add_argument("--share_tokens", type=int, default=0, help='0 - not share token; use each bin'
                                                                '1 - share token')
parser.add_argument("--seq_gen", type=str, default='addQ', help='addQ - add info token with timestamp (shared-token OURS). '
                                                                'NOadd - no info token (no-share Xshare variant).')
parser.add_argument("--objective", type=str, default='G2DYDTSP',
                    help='G2DYDTSP - OURS: time-aware generative objective (next token + next-event time). '
                         'NTP - plain next-token prediction; used by the ETHOS generation baseline and '
                         'forced internally for all downstream evaluation.')
parser.add_argument("--use_rope", type=int, default=1, help='1 - Use RoPE (OURS). '
                                                            '0 - No RoPE: learned absolute position embedding (ETHOS baseline).')
parser.add_argument("--pe_baseline", type=str, default=None, help='None - OURS (default). '
                                                                  'ETHOS - retained only for the generation-quality comparison.')
parser.add_argument("--multiple_rope_factor", type=int, default=1, help='0 - use one rope factor: Day as 1'
                                                                        '1 - use multiple rope factors')
parser.add_argument("--model_timestamp_rope_dim", type=int, default=40) # 512(model_hidden_dim)/ 8 (model_num_heads) = 64; 24-position/40-time
parser.add_argument("--use_temperature_adj", type=int, default=1, help='0 - No temperature_adj: Set temp to 1'
                                                                       '1 - Use temperature_adj')

# Evaluation args
parser.add_argument("--eval_seed", type=int, default=0)
parser.add_argument("--eval_max_length", type=int, default=2048)
parser.add_argument("--eval_overlap", type=int, default=512)

parser.add_argument("--eval_dataset", type=str, default='M4', help='M4 or eICU')
parser.add_argument("--eval_zero_shot", type=int, default=0, help='eval_dataset이 M4가 아닌 경우에만 True일 수 있음')
parser.add_argument("--eval_task_dir", type=str, default=os.path.join(DATA_ROOT, "PFM_downstream") + os.sep)
parser.add_argument("--eval_data_dir", type=str, default=os.path.join(DATA_ROOT, "PFM_downstream", "tensor_dt_saved") + os.sep)
parser.add_argument("--eval_load_pretrained", type=str, default=None, help='evaluate/finetune from a pretrained run folder, e.g. '
                                                                           'max_len2048_overlap512_h512_h8_l6_ff2048/fcriteria1_bin10_exp1_th10_share1_addQ_G2DYDTSP_rope:U1M1TS40_<TIMESTAMP>')
parser.add_argument("--eval_saved_path", type=str, default=None, help='')
parser.add_argument("--eval_finetune_batch_size", type=int, default=72)
parser.add_argument("--eval_finetune_epoch", type=int, default=10)
parser.add_argument("--eval_finetune_lr", type=float, default=5e-5)
parser.add_argument("--eval_ft_lr_decay", type=float, default=0.1)
parser.add_argument("--eval_ft_range", type=int, default=3, help='whether full FT or FT only head ' # TODO NOT done yet -> now always 3
                                                                       '0- FT only head'
                                                                       '1- FT head & Added embeddings'
                                                                       '2- FT head & All embeddings'
                                                                       '3- Full FT')

# DDP 추가 인자
parser.add_argument("--local_rank", type=int)
parser.add_argument("--rank", type=int)
parser.add_argument("--world_size", type=int)
args = parser.parse_args()

# === DDP 초기화 (가장 먼저 수행) ===
if not initialize_ddp():
    print("Failed to initialize DDP")
    raise AttributeError

do_train = True
if args.eval_saved_path is None:
    args.eval_saved_path = args.checkpoint_dir
if args.eval_load_pretrained is not None:
    do_train = False
    # Evaluation bypass training (Downstream tasks from pretrained checkpoint)
    args = update_args_from_json(args, f"{args.eval_saved_path}/{args.eval_load_pretrained}/args.json")

    # Re-pin the binning thresholds to the in-repo copy (args.json may carry an
    # absolute path from the original training machine).
    args.binning_threshold = _BINNING_DATA_DIR


# Remove impossible args combinations #
if args.use_rope == 0:
    # ETHOS baseline: no RoPE (learned absolute position embedding).
    assert args.multiple_rope_factor == 1 # default
    assert args.model_timestamp_rope_dim == 40 # default
if args.seq_gen == 'NOadd':
    assert args.share_tokens == 0
if args.objective == 'NTP':
    # NTP (ETHOS baseline / downstream eval): next-event-time prediction unused.
    assert args.pred_max_dist_hr == 24  # default; not used

if do_train:
    if args.resume_pretrain is not None:
        # ✅ 기존 폴더 재사용 (새 timestamp 폴더 생성 X)
        args.checkpoint_dir = os.path.join(args.checkpoint_dir, args.resume_pretrain, 'check_points')
        args.result_dir = os.path.join(args.result_dir, args.resume_pretrain, 'results')
        args.eval_load_pretrained = args.resume_pretrain
        if int(os.environ["RANK"]) == 0:
            print(f"[Resume] Resuming from: {args.checkpoint_dir}")
    else:
        timestamp = datetime.now().strftime("%m%d:%H%M%S")
        datasetting = f'max_len{args.sample_max_length}_overlap{args.sample_overlap}' \
                      f'_h{args.model_hidden_dim}_h{args.model_num_heads}_l{args.model_num_layers}_ff{args.model_d_ff}'
        processingsetting = f'f{args.data}_{args.bin}_share{args.share_tokens}_{args.seq_gen}_{args.objective}' \
                            f'_rope:U{args.use_rope}M{args.multiple_rope_factor}TS{args.model_timestamp_rope_dim}_{timestamp}'
        args.checkpoint_dir = os.path.join(args.checkpoint_dir, datasetting, processingsetting, 'check_points')
        args.result_dir = os.path.join(args.result_dir, datasetting, processingsetting, 'results')
        args.eval_load_pretrained = f'{datasetting}/{processingsetting}'
        if int(os.environ["RANK"]) == 0:
            save_args_to_json(args, os.path.dirname(args.result_dir) + '/args.json')
            os.makedirs(args.checkpoint_dir, exist_ok=True)
            os.makedirs(args.result_dir, exist_ok=True)

# 모델, 데이터셋
processor = key_value_unit_processer(args.data, args.binning_threshold)
config = token_bin_range(args, processor.inclusion_dict_processed) # 'decimal' for ori#, 'bins' for bin#

if int(os.environ["RANK"]) == 0 and do_train:
    save_args_to_json(config, os.path.dirname(args.result_dir)+'/configs.json')

tokenizer = MultiTypeTokenizer(config, args)
type_info = tokenizer.get_type_info()
args.vocab_size = type_info['total_vocab_size']
args.tokenizer_ranges = type_info['tokenizer_ranges']

if do_train:
    args.in_pretrain = True
    train_dataset, val_dataset = get_datasets(args, tokenizer, processor)
    if int(os.environ["RANK"]) == 0:
        print("\n=== 데이터셋 정보 ===")
        print(f'Train dataset len: {len(train_dataset)} / Valid dataset len: {len(val_dataset)}')
        # 타입별 정보 출력
        print("\n=== Tokenizer 타입별 정보 ===")
        type_info = tokenizer.get_type_info()
        for data_type, info in type_info.items():
            if data_type != 'total_vocab_size' and data_type != 'tokenizer_ranges':
                print(
                    f"{data_type}: idx={info['tokenizer_idx']}, vocab_size={info['vocab_size']}, offset={info['token_offset']}, type={info['type']}")
        print(f"Total vocabulary size: {type_info['total_vocab_size']}")
        print(f"Total tokenizer_ranges: {type_info['tokenizer_ranges']}")


    # type_info = tokenizer.get_type_info()
    # args.vocab_size = type_info['total_vocab_size']
    # args.tokenizer_ranges = type_info['tokenizer_ranges']

    model = TimestampTransformer(args)
    if int(os.environ["RANK"]) == 0:
        print("\n=== 모델 정보 ===")
        print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")


    trainer = TransformerTrainerDDP(model, train_dataset, val_dataset, tokenizer, args)
    # Resume할 체크포인트 결정 (best_model 우선, 없으면 가장 최근 epoch 체크포인트)
    resume_ckpt_path = None
    if args.resume_pretrain is not None:
        best_path = os.path.join(args.checkpoint_dir, "best_model.pt")
        if os.path.exists(best_path):
            resume_ckpt_path = best_path
        else:
            # best가 없으면 가장 최근 epoch 체크포인트 탐색
            ckpt_files = [f for f in os.listdir(args.checkpoint_dir) if f.startswith("checkpoint_epoch_")]
            if ckpt_files:
                latest = max(ckpt_files, key=lambda x: int(x.split("_")[-1].split(".")[0]))
                resume_ckpt_path = os.path.join(args.checkpoint_dir, latest)
        if int(os.environ["RANK"]) == 0:
            print(f"[Resume] Loading checkpoint: {resume_ckpt_path}")

    trainer.train(resume_checkpoint=resume_ckpt_path)

    del trainer
    raise AttributeError


# eval downstream task
set_seed(args.eval_seed, int(os.environ["RANK"]))

args.in_pretrain = False
original_data = args.data

if int(os.environ["RANK"]) == 0:
    save_args_to_json(args, f'{args.eval_saved_path}/{args.eval_load_pretrained}/args_dt.json')

# 각 데이터셋별로 독립적인 fine-tuning 수행
datasets_to_eval = ['criteria1']


for idx, data_type in enumerate(datasets_to_eval):
    if torch.distributed.is_initialized():
        torch.distributed.barrier()

    # 각 데이터셋마다 새로운 모델 인스턴스 생성
    args.data = data_type
    model = TimestampTransformer(args)

    # 새로운 데이터셋과 trainer 생성
    train_dataset, val_dataset = get_datasets(args, tokenizer, processor)
    trainer = TransformerTrainerDDP(model, train_dataset, val_dataset, tokenizer, args)

    if int(os.environ["RANK"]) == 0:
        print(f"\n=== Starting downstream task for data type {data_type} ===")

    # downstream task 수행
    trainer.downstream_tasks()

    # 명시적으로 메모리 정리
    del trainer
    del model
    del train_dataset
    del val_dataset

    # GPU 메모리 정리
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # 다른 프로세스들과 동기화
    if torch.distributed.is_initialized():
        torch.distributed.barrier()

    if int(os.environ["RANK"]) == 0:
        print(f"=== Completed downstream task for data type {data_type} ===\n")


'''
torchrun --nproc_per_node=4 main.py --world_size=4 --rank=0 --local_rank=0 ...
'''
